### ISSUE TITLE
Headline is disappearing

### ISSUE THREAD

**Issue by bl1nk** [BakeRolls/yarbs#2]
Not quite sure when this happens, but the headline saying "Heute" with all buttons needed for interaction is missing after some time.
<img width="400" alt="screen shot 2015-09-11 at 22 05 36" src="https://cloud.githubusercontent.com/assets/663247/9825084/67c0e090-58d1-11e5-8ac3-d80d708e94e7.png">

**Comment by bake** [comment]
This should already be fixed in aabc1ac471182437b39f62f48519588e6e879802 :)
