### ISSUE TITLE
How to quit Yarbs on OSX

### ISSUE THREAD

**Issue by Shobba** [BakeRolls/yarbs#4]
Hi,
a right click context menu (or similar) with the option to quit yarbs.app would be nice. Currently I don't see any other possibility than using OSX' activity monitor.

**Comment by bake** [comment]
Use cmd+q or update to 0.1.8 and click the questionmark :)
![screen shot 2015-09-23 at 17 20 26](https://cloud.githubusercontent.com/assets/1502822/10049356/66a84258-6217-11e5-9796-1eb5aa1be94b.png)

**Comment by Shobba** [comment]
Oh, didn't notice that :D Thanks, that's fine for me!
