### ISSUE TITLE
version numbers broken on macOS

### ISSUE THREAD

**Issue by core-code** [BakeRolls/yarbs#5]
i've downloaded Version '0.1.8' but when selecting it in the Finder and using 'Get Info' it shows Version '0.33.1'

i believe the '--version=0.33.1' in your package.json is the culprit

**Comment by bake** [comment]
Thank you, it is fixed in [v0.1.9](https://github.com/BakeRolls/yarbs/releases/tag/v0.1.9).

**Comment by core-code** [comment]
awesome, thanks!
